### ISSUE TITLE
List of blocked sites

### ISSUE THREAD

**Issue by ThiemNguyen** [247DigitalGroup/python-goose#1]
- [x] viralnova.com
- [x] salaam-news.com

Goose found correct top node, but was unable to fetch images inside it (403 forbidden error), thus it had to try getting opengraph images. It was lucky because the site had that kind of data.
Examples:
http://www.viralnova.com/family-on-the-moon/
http://salaam-news.com/2015/01/20/jameel-prizewinner-reinvents-the-iconic-middle-eastern-rug/

**Comment by canhduonguk** [comment]
[fixed] add user_agent when downloading images
