### ISSUE TITLE
businessinsider.com: img elements are removed prematurely

### ISSUE THREAD

**Issue by ThiemNguyen** [247DigitalGroup/python-goose#3]
Description:
- top_node is correct.
- the first p element which contains the img element got removed

Test case:
http://www.businessinsider.com/why-us-stocks-will-outperform-the-rest-of-the-world-2015-3

**Comment by ThiemNguyen** [comment]
@nautilus28 the `p` element which contains the main image is preserved if we comment out this line (crawler.py, line 164)

```
self.article.doc = self.cleaner.clean()
```

**Comment by canhduonguk** [comment]
okay, the cleaner should be fixed.
